moloni_es_login:
  resource: "moloni_login.yml"

_moloni_es_home:
  resource: "moloni_home.yml"

_moloni_es_documents:
  resource: "moloni_documents.yml"

_moloni_es_settings_index:
  resource: "settings/documents.yml"

_moloni_es_settings_prod:
  resource: "settings/products.yml"

_moloni_es_settings_auto:
  resource: "settings/automation.yml"

_moloni_es_settings_tools:
  resource: "settings/tools.yml"