_moloni_es_login:
  resource: "login/login.yml"

_moloni_es_orders:
  resource: "orders/orders.yml"

_moloni_es_documents:
  resource: "documents/documents.yml"

_moloni_es_settings_documents:
  resource: "settings/documents.yml"

_moloni_es_settings_products:
  resource: "settings/products.yml"

_moloni_es_settings_automation:
  resource: "settings/automation.yml"

_moloni_es_settings_tools:
  resource: "tools/tools.yml"
