_moloni_es_login:
  resource: "login/login.yml"

_moloni_es_orders:
  resource: "orders/orders.yml"

_moloni_es_documents:
  resource: "documents/documents.yml"

_moloni_es_settings:
  resource: "settings/settings.yml"

_moloni_es_tools:
  resource: "tools/tools.yml"
