moloni_es_login_home:
  path: /
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Login\Login::home'
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_login_submit:
  path: /
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Login\Login::submit'

moloni_es_login_retrievecode:
  path: /retrieveCode
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Login\Login::retrieveCode'

moloni_es_login_company_select:
  path: /company
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Login\Login::companySelect'
    _legacy_controller: 'Moloni'

moloni_es_login_company_submit:
  path: /companySubmit/{companyId}
  methods: [ GET ]
  defaults:
    _controller: 'Moloni\Controller\Admin\Login\Login::companySelectSubmit'
