moloni_es_login_home:
  path: /login
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Login::home'
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_login_submit:
  path: /login
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Login::submit'

moloni_es_login_retrievecode:
  path: /login/retrieveCode
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Login::retrieveCode'

moloni_es_login_company_select:
  path: /login/company
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Login::companySelect'

moloni_es_login_company_submit:
  path: /login/company
  methods: [ GET ]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Login::companySelectSubmit'
