moloni_es_registration_home:
  path: /
  methods: [GET,POST]
  defaults:
    _controller: moloni.controller.registration:home
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_registration_verify_form:
  path: /verifySlug
  methods: [POST]
  defaults:
    _controller: moloni.controller.registration:verifyForm
