moloni_es_registration_home:
  path: /registration/
  methods: [GET,POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Registration\Registration::home'
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'
