moloni_es_tools_home:
  path: /
  methods: [GET]
  defaults:
    _controller: moloni.controller.tools:home
    _legacy_controller: 'MoloniTools'
    _legacy_link: 'MoloniTools'

moloni_es_tools_reinstall_hooks:
  path: /reinstallHooks
  methods: [GET]
  defaults:
    _controller: moloni.controller.tools:reinstallHooks

moloni_es_tools_import_products:
  path: /importProducts
  methods: [POST]
  defaults:
    _controller: moloni.controller.tools:importProducts

moloni_es_tools_import_stocks:
  path: /importStocks
  methods: [POST]
  defaults:
    _controller: moloni.controller.tools:importStocks

moloni_es_tools_export_products:
  path: /exportProducts
  methods: [POST]
  defaults:
    _controller: moloni.controller.tools:exportProducts

moloni_es_tools_export_stocks:
  path: /exportStocks
  methods: [POST]
  defaults:
    _controller: moloni.controller.tools:exportStocks

moloni_es_tools_logout:
  path: /logout
  methods: [GET]
  defaults:
    _controller: moloni.controller.tools:logout
