moloni_es_tools_home:
  path: /tools
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Tools\Tools::home'
    _legacy_controller: 'MoloniTools'
    _legacy_link: 'MoloniTools'

moloni_es_tools_import_products:
  path: /tools/importProducts
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Tools\Tools::importProducts'

moloni_es_tools_import_categories:
  path: /tools/importCategories
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Tools\Tools::importCategories'

moloni_es_tools_reinstall_hooks:
  path: /tools/reinstallHooks
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Tools\Tools::reinstallHooks'

moloni_es_tools_sync_stock:
  path: /tools/syncStocks
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Tools\Tools::syncStocks'

moloni_es_tools_open_logs:
  path: /tools/openLogs
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Tools\Tools::openLogs'
    _legacy_controller: 'MoloniTools'
    _legacy_link: 'MoloniTools'

moloni_es_tools_delete_logs:
  path: /tools/deleteLogs
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Tools\Tools::deleteLogs'

moloni_es_tools_logout:
  path: /tools/logout
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Tools\Tools::logout'
