moloni_es_debug_home:
  path: /
  methods: [GET,POST]
  defaults:
    _controller: moloni.controller.debug:home
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_debug_check_attributes:
  path: /checkAttributesValidity
  methods: [GET,POST]
  defaults:
    _controller: moloni.controller.debug:checkAttributesValidity
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_debug_update_stock_from_moloni:
  path: /updateStockFromMoloni
  methods: [GET,POST]
  defaults:
    _controller: moloni.controller.debug:updateStockFromMoloni
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_debug_update_product_from_moloni:
  path: /updateProductFromMoloni
  methods: [GET,POST]
  defaults:
    _controller: moloni.controller.debug:updateProductFromMoloni
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_debug_insert_product_from_moloni:
  path: /insertProductFromMoloni
  methods: [ GET,POST ]
  defaults:
    _controller: moloni.controller.debug:insertProductFromMoloni
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_debug_update_stock_from_prestashop:
  path: /updateStockFromPrestashop
  methods: [GET,POST]
  defaults:
    _controller: moloni.controller.debug:updateStockFromPrestashop
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_debug_update_product_from_prestashop:
  path: /updateProductFromPrestashop
  methods: [GET,POST]
  defaults:
    _controller: moloni.controller.debug:updateProductFromPrestashop
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_debug_insert_product_from_prestashop:
  path: /insertProductFromPrestashop
  methods: [ GET,POST ]
  defaults:
    _controller: moloni.controller.debug:insertProductFromPrestashop
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'

moloni_es_debug_dump_product_associations:
  path: /dumpProductAssociations
  methods: [ GET,POST ]
  defaults:
    _controller: moloni.controller.debug:dumpProductAssociations
    _legacy_controller: 'Moloni'
    _legacy_link: 'Moloni'