moloni_es_documents_home:
  path: /
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Documents\Documents::home'
    _legacy_controller: 'MoloniDocuments'
    _legacy_link: 'MoloniDocuments'

moloni_es_documents_download:
  path: /download/
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Documents\Documents::download'

moloni_es_documents_view:
  path: /view/
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Documents\Documents::view'

moloni_es_documents_restore:
  path: /restore/
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Documents\Documents::restore'
