moloni_es_documents_home:
  path: /
  methods: [GET]
  defaults:
    _controller: moloni.controller.documents:home
    _legacy_controller: 'MoloniDocuments'
    _legacy_link: 'MoloniDocuments'

moloni_es_documents_download:
  path: /download/
  methods: [GET]
  defaults:
    _controller: moloni.controller.documents:download

moloni_es_documents_view:
  path: /view/
  methods: [GET]
  defaults:
    _controller: moloni.controller.documents:view

moloni_es_documents_restore:
  path: /restore/
  methods: [GET]
  defaults:
    _controller: moloni.controller.documents:restore
