moloni_es_documents_home:
  path: /documents
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Documents::home'
    _legacy_controller: 'MoloniDocuments'
    _legacy_link: 'MoloniDocuments'

moloni_es_documents_download:
  path: /documents/download/{documentId}
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Documents::download'

moloni_es_documents_restore:
  path: /documents/restore/{orderId}
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Documents::restore'

moloni_es_documents_open:
  path: /documents/open/{documentId}
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Documents::open'
