services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Moloni repositories

  moloni.repository.orders:
    class: Moloni\Repository\OrdersRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  moloni.repository.settings:
    class: Moloni\Repository\MoloniSettingsRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - Moloni\Entity\MoloniSettings

  # Moloni services

  moloni.services.context:
    class: Moloni\Services\MoloniContext
    arguments:
      - "@doctrine.orm.entity_manager"

  # Moloni listeners

  moloni.listener.authentication:
    class: Moloni\EventListener\AuthenticationListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller }


  # Moloni form service di

  moloni.settings.form:
    class: Moloni\Form\Settings\SettingsFormHandler
    public: true
    autowire: true
    autoconfigure: false
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@moloni.settings.form_data_provider'

  moloni.settings.form_data_provider:
    class: 'Moloni\Form\Settings\SettingsFormDataProvider'
    arguments:
      - '@translator'
      - '@moloni.repository.settings'
      - '@=service("prestashop.adapter.legacy.context").getLanguage().id'

  moloni.settings.form_type:
    class: Moloni\Form\Settings\SettingsFormType
    parent: 'form.type.translatable.aware'
    public: true
    autowire: true
    autoconfigure: false
    tags:
      - { name: form.type }
    arguments:
      - '@moloni.settings.form_data_provider'
