moloni_es_settings_automation:
  path: /settings/automation
  methods: [GET, POST]
  defaults:
    _controller: 'Moloni\ES\Controllers\Settings\Automation::display'
    _legacy_controller: 'MoloniSettings'

moloni_es_settings_automation_submit:
  path: /settings/automation/submit
  methods: [POST]
  defaults:
    _controller: 'Moloni\ES\Controllers\Settings\Automation::submitted'