moloni_es_settings_automation:
  path: /settings/automation
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Settings\Automation::home'
    _legacy_controller: 'MoloniSettings'

moloni_es_settings_automation_save:
  path: /settings/automation/save
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controllers\Admin\Settings\Automation::save'
