moloni_es_settings_documents:
  path: /settings/documents
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Settings\Documents::display'
    _legacy_controller: 'MoloniSettings'
    _legacy_link: 'MoloniSettings'

moloni_es_settings_documents_save:
  path: /settings/documents/save
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Settings\Documents::save'
