moloni_es_settings_products:
  path: /settings/products
  methods: [GET, POST]
  defaults:
    _controller: 'Moloni\Controllers\Settings\Products::display'
    _legacy_controller: 'MoloniSettings'

moloni_es_settings_products_submit:
  path: /settings/products/submit
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controllers\Settings\Products::submitted'
