moloni_es_settings_products:
  path: /settings/products
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Settings\Products::home'
    _legacy_controller: 'MoloniSettings'

moloni_es_settings_products_save:
  path: /settings/products/save
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Settings\Products::save'
