moloni_es_settings_home:
  path: /
  methods: [GET,POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Settings\Settings::home'
    _legacy_controller: 'MoloniSettings'
    _legacy_link: 'MoloniSettings'
