moloni_es_products_home:
  path: /
  methods: [GET]
  defaults:
    _controller: 'Moloni\Controller\Admin\Products\Products::home'
    _legacy_controller: 'MoloniTools'
    _legacy_link: 'MoloniTools'

moloni_es_products_export_product:
  path: /exportProduct
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Products\Products::exportProduct'
    _legacy_controller: 'MoloniTools'
    _legacy_link: 'MoloniTools'

moloni_es_products_import_stock:
  path: /importStock
  methods: [POST]
  defaults:
    _controller: 'Moloni\Controller\Admin\Products\Products::importStock'
    _legacy_controller: 'MoloniTools'
    _legacy_link: 'MoloniTools'