moloni_es_products_home:
  path: /
  methods: [GET]
  defaults:
    _controller: moloni.controller.products:home
    _legacy_controller: 'MoloniTools'
    _legacy_link: 'MoloniTools'

moloni_es_products_export_product:
  path: /exportProduct
  methods: [POST]
  defaults:
    _controller: moloni.controller.products:exportProduct

moloni_es_products_import_stock:
  path: /importStock
  methods: [POST]
  defaults:
    _controller: moloni.controller.products:importStock