moloni_es_orders_home:
  path: /
  methods: [GET]
  defaults:
    _controller: moloni.controller.orders:home
    _legacy_controller: 'MoloniOrders'
    _legacy_link: 'MoloniOrders'

moloni_es_orders_create:
  path: /createDocument
  methods: [GET, POST]
  defaults:
    _controller: moloni.controller.orders:create

moloni_es_orders_discard:
  path: /clearInvoice
  methods: [GET, POST]
  defaults:
    _controller: moloni.controller.orders:discard
