services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  moloni.services.authentication:
    class: Moloni\EventListener\AuthenticationListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  moloni.services.context:
    class: Moloni\Services\MoloniContext
    arguments:
      - "@doctrine.orm.entity_manager"
